package com.customlibrary.imagedetaction.utils

object Constant {
    const val MESSAGE_TYPE_TEXT = "text"
    const val MESSAGE_TYPE_STORY_REPLAY = "reply_story"
    const val MESSAGE_TYPE_KICK_OUT = "kickout"
    const val MESSAGE_TYPE_BAN = "ban"
    const val MESSAGE_TYPE_SLAP = "slap"
    const val AGORA_CHANNEL_NAME_PREFIX = "meet_"
    const val MESSAGE_TYPE_DELETE = "delete"
    const val MESSAGE_TYPE_EDITED = "edited"
    const val MESSAGE_TYPE_SAVE = "save"
    const val MESSAGE_TYPE_FORWARD = "forward"
    const val MESSAGE_TYPE_IMAGE = "image"
    const val MESSAGE_TYPE_REPLY = "reply"
    const val PHOTO = "photo"
    const val VIDEO = "video"
    const val MESSAGE_TYPE_JOIN = "join"
    const val MESSAGE_TYPE_LEFT = "left"

    const val MESSAGE_TYPE_RESTRICT = "restrict"
    const val MESSAGE_TYPE_SEND_GIFT = "send_gift"
    const val MESSAGE_TYPE_REQUEST_GIFT = "request_coins"
    const val TOKEN = "token"
    const val LIKE = "like"
    const val UNLIKE = "unlike"
    const val CALL_TYPE_MISSED = "missed"
    const val CALL_TYPE_VIDEO = "video"
    const val CALL_TYPE_CALLING = "calling"
    const val TYPE_SHORTS = "shorts"
    const val UNBLOCK_STATUS = "unblock"
    const val GAME_RESULT_WIN = "win"
    const val GAME_RESULT_LOSS = "loss"
    const val GAME_RESULT_DRAW = "draw"
    const val JOIN_CHALLENGE = "Join Challenge"
    const val DOWNLOAD_SHORTS = "Download Shorts"
    const val ADD_STORY = "Add Story"
    const val REPOST_POST = "Repost Post"
    const val SEND_GIFT = "Send Gift"
    const val REPORT_CONTENT = "Report Content"
    const val SHARE_CONTENT = "Share Content"
    const val COMMENT_CONTENT = "Comment Content"
    const val LIKE_CONTENT = "Like Content"
    const val SCREEN_TIME = "Screen Time"
    const val TOTAL_HOURS_USER_LIVE_IN_THIS_MONTH = "Total hours user live in this month"

    // Mix panel params
    const val CHALLENGE_ID = "challenge_id"
    const val POST_ID = "post_id"
    const val SHORTS_ID = "shorts_id"
    const val CONTENT_TYPE = "content_type"
    const val CONTENT_ID = "content_id"
    const val SCREEN_TYPE = "screen_type"
    const val LIVE_ID = "live_id"
    const val ROLE = "role"
    const val START_TIME = "start_time"
    const val END_TIME = "end_time"
    const val TOTAL_TIME_OF_THIS_MONTH = "total_time_of_this_month"

    var EXCHANGE_RATE = "1.0"
    var CENT_VALUE = "0.0032"
    var CURRENCY_SYMBOL = "$"
    var CLICK_COUNT = 0

    // Report For
    const val SHORT = "short"
    const val STORY = "story"
    const val POST = "post"
    const val LIVE = "live"
    const val DISMISS = "dismiss"
    const val FIXED_10_MILLISECOND = 10L
    const val FIXED_50_MILLISECOND = 50L
    const val FIXED_100_MILLISECOND = 100L
    const val FIXED_200_MILLISECOND = 200L
    const val FIXED_500_MILLISECOND = 500L
    const val FIXED_1000_MILLISECOND = 1000L
    const val FIXED_2000_MILLISECOND = 2000L
    const val FIXED_3000_MILLISECOND = 3000L
    const val FIXED_4000_MILLISECOND = 4000L
    const val FIXED_5000_MILLISECOND = 5000L
    const val FIXED_10000_MILLISECOND = 10000L
    const val FIXED_30000_MILLISECOND = 30000L
    const val FIX_400_MILLISECOND = 400L
    const val FIX_500_MILLISECOND = 500L
    const val FIX_100_MILLISECOND = 100L
    const val FIXED_MINUS_13_INT = -13
    const val FIXED_1_INT = 1
    const val FIXED_2_INT = 2
    const val FIXED_3_INT = 3
    const val FIXED_4_INT = 4
    const val FIXED_5_INT = 5
    const val FIXED_6_INT = 6
    const val FIXED_7_INT = 7
    const val FIXED_8_INT = 8
    const val FIXED_9_INT = 9
    const val FIXED_10_INT = 10
    const val FIXED_12_INT = 12
    const val FIXED_16_INT = 16
    const val FIXED_20_INT = 20
    const val FIXED_24_INT = 24
    const val FIXED_29_INT = 29
    const val FIXED_30_INT = 30
    const val FIXED_40_INT = 40
    const val FIXED_50_INT = 50
    const val FIXED_60_INT = 60
    const val FIXED_70_INT = 70
    const val FIXED_75_INT = 75
    const val FIXED_80_INT = 80
    const val FIXED_90_INT = 90
    const val FIXED_100_INT = 100
    const val FIXED_121_INT = 121
    const val FIXED_130_INT = 130
    const val FIXED_150_INT = 150
    const val FIXED_160_INT = 160
    const val FIXED_200_INT = 200
    const val FIXED_230_INT = 230
    const val FIXED_270_INT = 270
    const val FIXED_255_INT = 255
    const val FIXED_300_INT = 300
    const val FIXED_365_INT = 365
    const val FIXED_500_INT = 500
    const val FIXED_1000_INT = 1000
    const val FIXED_1024_INT = 1024
    const val FIXED_1887_INT = 1887
    const val FIXED_3600_INT = 3600
    const val FIXED_4096_INT = 4096
    const val FIXED_10000_INT = 10000
    const val FIXED_1000000_INT = 1000000
    const val FIXED_0_POINT_5_FLOAT = 0.5f
    const val FIXED_10_FLOAT = 10.0f
    const val FIXED_15_FLOAT = 15.0f
    const val FIXED_25_FLOAT = 25.0f
    const val FIXED_30_FLOAT = 30.0f
    const val FIXED_40_FLOAT = 40.0f
    const val FIXED_50_FLOAT = 50F
    const val FIXED_100_FLOAT = 100.0f
    const val FIXED_210_FLOAT = 210.0f
    const val FIXED_MARGIN_40 = 40
    const val FIX_5000 = 5000
    const val COLOR_0xFFFFFF = 0xFFFFFF

    // MessageType
    const val SHORTS = "shorts"
    const val GIFT = "gift"
    const val CHALLENGE = "challenge"
    const val FOLLOW = "Follow"
    const val HOST_INVITE = "host_invite"
    const val ALL = "All"
    const val COMMENT = "comment"
    const val SENT_YOU_FOLLOW_REQUEST = "sent you follow request"
    const val STRING_NULL = "null"
    const val COVER = "Cover"
    const val FOLDER = "Folder"
    const val TAP_TO_SELECT = "Tap to select"
    const val CAMERA = "Camera"
    const val MAXIMUM_4_LINES_ARE_ALLOWED = "Maximum 4 lines are allowed"
    const val TIME_FORMAT = "dd MMM yyyy,HH:mm a"
}
